# Generated by Django 2.1.3 on 2018-11-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('parent_name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('parent_passport', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('student_passport', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('student_SNILS', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('parent_phone', models.CharField(blank=True, default=None, max_length=48, null=True)),
                ('student_address', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('class_number', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('form_master', models.CharField(blank=True, default=None, max_length=128, null=True)),
            ],
        ),
    ]
