# Generated by Django 2.1.3 on 2018-11-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.CharField(max_length=128)),
                ('classroom', models.CharField(max_length=128)),
                ('teacher', models.CharField(max_length=128)),
                ('day_of_the_week', models.CharField(max_length=128)),
                ('lesson_number', models.CharField(max_length=128)),
                ('subject', models.CharField(max_length=128)),
            ],
        ),
    ]
