# Generated by Django 2.1.3 on 2018-11-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolEnrolment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=128)),
                ('parent_name', models.CharField(max_length=128)),
                ('contract_number', models.CharField(max_length=128)),
                ('contract_date', models.CharField(max_length=128)),
                ('parent_passport', models.CharField(max_length=10)),
                ('student_passport', models.CharField(max_length=10)),
                ('student_SNILS', models.CharField(max_length=10)),
                ('parent_phone', models.CharField(max_length=48)),
                ('student_address', models.CharField(max_length=128)),
            ],
        ),
    ]
